apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c396tjwya-python 
  janus-idp.io/tekton: c396tjwya-python
  backstage.io/kubernetes-id: c396tjwya-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c396tjwya-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  